In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook

In [21]:
df_link_id = pd.read_csv('input.csv', sep='\t')

INDEX = 1
cur = df_link_id[df_link_id['INDEX'] == INDEX]
INDEX = INDEX + 1

while df_link_id['INDEX'].isna().sum() > 0:
    to = df_link_id[(df_link_id['INDEX'].isna()) & (df_link_id['tF_ID'] == cur['tT_ID'].item())]
    if len(set(to['LINK_ID'])) == 1:
        to = to.head(1)
        df_link_id.at[to.index, 'INDEX'] = INDEX
    elif len(to) > 1:
        temp = to
        to = to[to['tT_ID'] != cur['tF_ID'].item()]
        if len(to) == 0:
            to = temp
        if len(to) > 1:
            print(df_link_id[df_link_id['INDEX'].notna()].sort_values('INDEX')[['F_ID', 'LINK_ID', 'T_ID', '노선ID', '노선번호', 'INDEX']])
            print(to[['F_ID', 'LINK_ID', 'T_ID', '노선ID', '노선번호', 'INDEX']])
            rid = int(input('ROW_ID: '))
            to = to[to.index == rid]
        df_link_id.at[to.index, 'INDEX'] = INDEX
    else:
        df_link_id.at[df_link_id[(df_link_id['INDEX'].isna()) & (df_link_id['tF_ID'] == cur['tT_ID'].item())].index, 'INDEX'] = INDEX
        to = df_link_id[df_link_id['INDEX'] == INDEX]
    INDEX = INDEX + 1
    cur = to
    
# df_link_id.sort_values('INDEX').to_csv('output.csv', index=False, encoding='utf-8-sig')
df_link_id.sort_values('INDEX')[['F_ID','LINK_ID','T_ID','경도(생성됨)','기하 도형','위도(생성됨)','노선ID','노선번호','INDEX'
]].to_csv('output.csv', index=False, header=False, encoding='utf-8-sig')

           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
49   1650029400  1650095900  1650025600   NaN  303-1_변경   31.0
57   1650025600  1650083000  1650026700   NaN  303-1_변경   32.0
54   1650026700  1650104000  1650031700   NaN  303-1_변경   33.0
42   1650031700  1650105600  1650032200   NaN  303-1_변경   34.0
36   1650032200  1650105800  1650032000   NaN  303-1_변경   35.0
39   1650032000  1650105000  1650031900   NaN  303-1_변경   36.0
40   1650031900  1650109000  1650034600   NaN  303-1_변경   37.0
33   1650034600  1650113000  1650033400   NaN  303-1_변경   38.0
35   1650033400  1650108700  1650000600   NaN  303-1_변경   39.0
97   1650000600  1650000200  1650000100   NaN  303-1_변경   40.0
102  1650000100  1650000400  1650000200   NaN  303-1_변경   41.0
100  1650000200  1650000600  1650000300   NaN  303-1_변경   42.0
98   1650000300  1650153300  1650051500   NaN  303-1_변경   43.0
19   1650051500  1650154200  1650034700   NaN  303-1_변경   44.0
31   1650034700  1650140000  1650047100   NaN  303-1_변경   45.0
23   1650047100  1650139800  1650047300   NaN  303-1_변경   46.0
20   1650047300  1650140300  1650045800   NaN  303-1_변경   47.0
25   1650045800  1650140100  1650045700   NaN  303-1_변경   48.0
27   1650045700  1650136700  1650005000   NaN  303-1_변경   49.0
74   1650005000  1650023000  1650004900   NaN  303-1_변경   50.0
76   1650004900  1650180200  1650053800   NaN  303-1_변경   51.0
11   1650053800  1650161900  1640042200   NaN  303-1_변경   52.0
112  1640042200  1640133200  1640039900   NaN  303-1_변경   53.0
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
113  1640039900  1640146400  1640019100   NaN  303-1_변경    NaN
114  1640039900  1640141100  1640044800   NaN  303-1_변경    NaN
ROW_ID: 113
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
33   1650034600  1650113000  1650033400   NaN  303-1_변경   38.0
35   1650033400  1650108700  1650000600   NaN  303-1_변경   39.0
97   1650000600  1650000200  1650000100   NaN  303-1_변경   40.0
102  1650000100  1650000400  1650000200   NaN  303-1_변경   41.0
100  1650000200  1650000600  1650000300   NaN  303-1_변경   42.0
98   1650000300  1650153300  1650051500   NaN  303-1_변경   43.0
19   1650051500  1650154200  1650034700   NaN  303-1_변경   44.0
31   1650034700  1650140000  1650047100   NaN  303-1_변경   45.0
23   1650047100  1650139800  1650047300   NaN  303-1_변경   46.0
20   1650047300  1650140300  1650045800   NaN  303-1_변경   47.0
25   1650045800  1650140100  1650045700   NaN  303-1_변경   48.0
27   1650045700  1650136700  1650005000   NaN  303-1_변경   49.0
74   1650005000  1650023000  1650004900   NaN  303-1_변경   50.0
76   1650004900  1650180200  1650053800   NaN  303-1_변경   51.0
11   1650053800  1650161900  1640042200   NaN  303-1_변경   52.0
112  1640042200  1640133200  1640039900   NaN  303-1_변경   53.0
113  1640039900  1640146400  1640019100   NaN  303-1_변경   54.0
137  1640019100  1640061400  1640000900   NaN  303-1_변경   55.0
142  1640000900  1640005500  1640018300   NaN  303-1_변경   56.0
138  1640018300  1640059300  1640001200   NaN  303-1_변경   57.0
140  1640001200  1640107300  1640031900   NaN  303-1_변경   58.0
132  1640031900  1640102400  1640033000   NaN  303-1_변경   59.0
125  1640033000  1640106900  1640032000   NaN  303-1_변경   60.0
129  1640032000  1640103000  1640032100   NaN  303-1_변경   61.0
127  1640032100  1640103100  1640027400   NaN  303-1_변경   62.0
133  1640027400  1640151100  1640042800   NaN  303-1_변경   63.0
110  1640042800  1640148600  1640039700   NaN  303-1_변경   64.0
115  1640039700  1640152800  1640045300   NaN  303-1_변경   65.0
104  1640045300  1640153300  1640042700   NaN  303-1_변경   66.0
111  1640042700  1640128800  1640038600   NaN  303-1_변경   67.0

[67 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
122  1640038600  1650161600  1640038500   NaN  303-1_변경    NaN
123  1640038600  1640136500  1640038800   NaN  303-1_변경    NaN
ROW_ID: 123
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
19   1650051500  1650154200  1650034700   NaN  303-1_변경   44.0
31   1650034700  1650140000  1650047100   NaN  303-1_변경   45.0
23   1650047100  1650139800  1650047300   NaN  303-1_변경   46.0
20   1650047300  1650140300  1650045800   NaN  303-1_변경   47.0
25   1650045800  1650140100  1650045700   NaN  303-1_변경   48.0
27   1650045700  1650136700  1650005000   NaN  303-1_변경   49.0
74   1650005000  1650023000  1650004900   NaN  303-1_변경   50.0
76   1650004900  1650180200  1650053800   NaN  303-1_변경   51.0
11   1650053800  1650161900  1640042200   NaN  303-1_변경   52.0
112  1640042200  1640133200  1640039900   NaN  303-1_변경   53.0
113  1640039900  1640146400  1640019100   NaN  303-1_변경   54.0
137  1640019100  1640061400  1640000900   NaN  303-1_변경   55.0
142  1640000900  1640005500  1640018300   NaN  303-1_변경   56.0
138  1640018300  1640059300  1640001200   NaN  303-1_변경   57.0
140  1640001200  1640107300  1640031900   NaN  303-1_변경   58.0
132  1640031900  1640102400  1640033000   NaN  303-1_변경   59.0
125  1640033000  1640106900  1640032000   NaN  303-1_변경   60.0
129  1640032000  1640103000  1640032100   NaN  303-1_변경   61.0
127  1640032100  1640103100  1640027400   NaN  303-1_변경   62.0
133  1640027400  1640151100  1640042800   NaN  303-1_변경   63.0
110  1640042800  1640148600  1640039700   NaN  303-1_변경   64.0
115  1640039700  1640152800  1640045300   NaN  303-1_변경   65.0
104  1640045300  1640153300  1640042700   NaN  303-1_변경   66.0
111  1640042700  1640128800  1640038600   NaN  303-1_변경   67.0
123  1640038600  1640136500  1640038800   NaN  303-1_변경   68.0
121  1640038800  1640115000  1640038900   NaN  303-1_변경   69.0
118  1640038900  1640115100  1640039000   NaN  303-1_변경   70.0
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0

[73 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
198  1610002700  1610216800  1610064600   NaN  303-1_변경    NaN
199  1610002700  1610216700  1610062300   NaN  303-1_변경    NaN
ROW_ID: 199
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
23   1650047100  1650139800  1650047300   NaN  303-1_변경   46.0
20   1650047300  1650140300  1650045800   NaN  303-1_변경   47.0
25   1650045800  1650140100  1650045700   NaN  303-1_변경   48.0
27   1650045700  1650136700  1650005000   NaN  303-1_변경   49.0
74   1650005000  1650023000  1650004900   NaN  303-1_변경   50.0
76   1650004900  1650180200  1650053800   NaN  303-1_변경   51.0
11   1650053800  1650161900  1640042200   NaN  303-1_변경   52.0
112  1640042200  1640133200  1640039900   NaN  303-1_변경   53.0
113  1640039900  1640146400  1640019100   NaN  303-1_변경   54.0
137  1640019100  1640061400  1640000900   NaN  303-1_변경   55.0
142  1640000900  1640005500  1640018300   NaN  303-1_변경   56.0
138  1640018300  1640059300  1640001200   NaN  303-1_변경   57.0
140  1640001200  1640107300  1640031900   NaN  303-1_변경   58.0
132  1640031900  1640102400  1640033000   NaN  303-1_변경   59.0
125  1640033000  1640106900  1640032000   NaN  303-1_변경   60.0
129  1640032000  1640103000  1640032100   NaN  303-1_변경   61.0
127  1640032100  1640103100  1640027400   NaN  303-1_변경   62.0
133  1640027400  1640151100  1640042800   NaN  303-1_변경   63.0
110  1640042800  1640148600  1640039700   NaN  303-1_변경   64.0
115  1640039700  1640152800  1640045300   NaN  303-1_변경   65.0
104  1640045300  1640153300  1640042700   NaN  303-1_변경   66.0
111  1640042700  1640128800  1640038600   NaN  303-1_변경   67.0
123  1640038600  1640136500  1640038800   NaN  303-1_변경   68.0
121  1640038800  1640115000  1640038900   NaN  303-1_변경   69.0
118  1640038900  1640115100  1640039000   NaN  303-1_변경   70.0
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0
199  1610002700  1610216700  1610062300   NaN  303-1_변경   74.0
158  1610062300  1610213000  1610002100   NaN  303-1_변경   75.0

[75 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
200  1610002100  1610215400  1610002700   NaN  303-1_변경    NaN
201  1610002100  1610003000  1610020100   NaN  303-1_변경    NaN
ROW_ID: 201
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
125  1640033000  1640106900  1640032000   NaN  303-1_변경   60.0
129  1640032000  1640103000  1640032100   NaN  303-1_변경   61.0
127  1640032100  1640103100  1640027400   NaN  303-1_변경   62.0
133  1640027400  1640151100  1640042800   NaN  303-1_변경   63.0
110  1640042800  1640148600  1640039700   NaN  303-1_변경   64.0
115  1640039700  1640152800  1640045300   NaN  303-1_변경   65.0
104  1640045300  1640153300  1640042700   NaN  303-1_변경   66.0
111  1640042700  1640128800  1640038600   NaN  303-1_변경   67.0
123  1640038600  1640136500  1640038800   NaN  303-1_변경   68.0
121  1640038800  1640115000  1640038900   NaN  303-1_변경   69.0
118  1640038900  1640115100  1640039000   NaN  303-1_변경   70.0
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0
199  1610002700  1610216700  1610062300   NaN  303-1_변경   74.0
158  1610062300  1610213000  1610002100   NaN  303-1_변경   75.0
201  1610002100  1610003000  1610020100   NaN  303-1_변경   76.0
180  1610020100  1610055800  1610000800   NaN  303-1_변경   77.0
203  1610000800  1610001300  1610000600   NaN  303-1_변경   78.0
205  1610000600  1610000400  1610019900   NaN  303-1_변경   79.0
181  1610019900  1610071900  1610025900   NaN  303-1_변경   80.0
175  1610025900  1610072500  1610026100   NaN  303-1_변경   81.0
173  1610026100  1610072600  1610025500   NaN  303-1_변경   82.0
178  1610025500  1610072100  1610005800   NaN  303-1_변경   83.0
190  1610005800  1610020000  1610006500   NaN  303-1_변경   84.0
189  1610006500  1610019400  1610019300   NaN  303-1_변경   85.0
183  1610019300  1610053200  1610019200   NaN  303-1_변경   86.0
184  1610019200  1610053400  1610005500   NaN  303-1_변경   87.0
191  1610005500  1610015800  1610004200   NaN  303-1_변경   88.0
195  1610004200  1610013300  1610049100   NaN  303-1_변경   89.0

[89 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
166  1610049100  1610214800  1610069800   NaN  303-1_변경    NaN
167  1610049100  1610170800  1610068500   NaN  303-1_변경    NaN
ROW_ID: 167
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
129  1640032000  1640103000  1640032100   NaN  303-1_변경   61.0
127  1640032100  1640103100  1640027400   NaN  303-1_변경   62.0
133  1640027400  1640151100  1640042800   NaN  303-1_변경   63.0
110  1640042800  1640148600  1640039700   NaN  303-1_변경   64.0
115  1640039700  1640152800  1640045300   NaN  303-1_변경   65.0
104  1640045300  1640153300  1640042700   NaN  303-1_변경   66.0
111  1640042700  1640128800  1640038600   NaN  303-1_변경   67.0
123  1640038600  1640136500  1640038800   NaN  303-1_변경   68.0
121  1640038800  1640115000  1640038900   NaN  303-1_변경   69.0
118  1640038900  1640115100  1640039000   NaN  303-1_변경   70.0
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0
199  1610002700  1610216700  1610062300   NaN  303-1_변경   74.0
158  1610062300  1610213000  1610002100   NaN  303-1_변경   75.0
201  1610002100  1610003000  1610020100   NaN  303-1_변경   76.0
180  1610020100  1610055800  1610000800   NaN  303-1_변경   77.0
203  1610000800  1610001300  1610000600   NaN  303-1_변경   78.0
205  1610000600  1610000400  1610019900   NaN  303-1_변경   79.0
181  1610019900  1610071900  1610025900   NaN  303-1_변경   80.0
175  1610025900  1610072500  1610026100   NaN  303-1_변경   81.0
173  1610026100  1610072600  1610025500   NaN  303-1_변경   82.0
178  1610025500  1610072100  1610005800   NaN  303-1_변경   83.0
190  1610005800  1610020000  1610006500   NaN  303-1_변경   84.0
189  1610006500  1610019400  1610019300   NaN  303-1_변경   85.0
183  1610019300  1610053200  1610019200   NaN  303-1_변경   86.0
184  1610019200  1610053400  1610005500   NaN  303-1_변경   87.0
191  1610005500  1610015800  1610004200   NaN  303-1_변경   88.0
195  1610004200  1610013300  1610049100   NaN  303-1_변경   89.0
167  1610049100  1610170800  1610068500   NaN  303-1_변경   90.0

[90 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
149  1610068500  1610167100  1610049200   NaN  303-1_변경    NaN
150  1610068500  1610166700  1610068600   NaN  303-1_변경    NaN
ROW_ID: 149
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
104  1640045300  1640153300  1640042700   NaN  303-1_변경   66.0
111  1640042700  1640128800  1640038600   NaN  303-1_변경   67.0
123  1640038600  1640136500  1640038800   NaN  303-1_변경   68.0
121  1640038800  1640115000  1640038900   NaN  303-1_변경   69.0
118  1640038900  1640115100  1640039000   NaN  303-1_변경   70.0
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0
199  1610002700  1610216700  1610062300   NaN  303-1_변경   74.0
158  1610062300  1610213000  1610002100   NaN  303-1_변경   75.0
201  1610002100  1610003000  1610020100   NaN  303-1_변경   76.0
180  1610020100  1610055800  1610000800   NaN  303-1_변경   77.0
203  1610000800  1610001300  1610000600   NaN  303-1_변경   78.0
205  1610000600  1610000400  1610019900   NaN  303-1_변경   79.0
181  1610019900  1610071900  1610025900   NaN  303-1_변경   80.0
175  1610025900  1610072500  1610026100   NaN  303-1_변경   81.0
173  1610026100  1610072600  1610025500   NaN  303-1_변경   82.0
178  1610025500  1610072100  1610005800   NaN  303-1_변경   83.0
190  1610005800  1610020000  1610006500   NaN  303-1_변경   84.0
189  1610006500  1610019400  1610019300   NaN  303-1_변경   85.0
183  1610019300  1610053200  1610019200   NaN  303-1_변경   86.0
184  1610019200  1610053400  1610005500   NaN  303-1_변경   87.0
191  1610005500  1610015800  1610004200   NaN  303-1_변경   88.0
195  1610004200  1610013300  1610049100   NaN  303-1_변경   89.0
167  1610049100  1610170800  1610068500   NaN  303-1_변경   90.0
149  1610068500  1610167100  1610049200   NaN  303-1_변경   91.0
165  1610049200  1610144200  1610049500   NaN  303-1_변경   92.0
163  1610049500  1610143900  1610049000   NaN  303-1_변경   93.0
168  1610049000  1610170900  1610067600   NaN  303-1_변경   94.0
152  1610067600  1610168400  1610010000   NaN  303-1_변경   95.0

[95 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
186  1610010000  1610170300  1610068700   NaN  303-1_변경    NaN
187  1610010000  1610170200  1610068800   NaN  303-1_변경    NaN
188  1610010000  1610149500  1610051200   NaN  303-1_변경    NaN
ROW_ID: 187
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
123  1640038600  1640136500  1640038800   NaN  303-1_변경   68.0
121  1640038800  1640115000  1640038900   NaN  303-1_변경   69.0
118  1640038900  1640115100  1640039000   NaN  303-1_변경   70.0
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0
199  1610002700  1610216700  1610062300   NaN  303-1_변경   74.0
158  1610062300  1610213000  1610002100   NaN  303-1_변경   75.0
201  1610002100  1610003000  1610020100   NaN  303-1_변경   76.0
180  1610020100  1610055800  1610000800   NaN  303-1_변경   77.0
203  1610000800  1610001300  1610000600   NaN  303-1_변경   78.0
205  1610000600  1610000400  1610019900   NaN  303-1_변경   79.0
181  1610019900  1610071900  1610025900   NaN  303-1_변경   80.0
175  1610025900  1610072500  1610026100   NaN  303-1_변경   81.0
173  1610026100  1610072600  1610025500   NaN  303-1_변경   82.0
178  1610025500  1610072100  1610005800   NaN  303-1_변경   83.0
190  1610005800  1610020000  1610006500   NaN  303-1_변경   84.0
189  1610006500  1610019400  1610019300   NaN  303-1_변경   85.0
183  1610019300  1610053200  1610019200   NaN  303-1_변경   86.0
184  1610019200  1610053400  1610005500   NaN  303-1_변경   87.0
191  1610005500  1610015800  1610004200   NaN  303-1_변경   88.0
195  1610004200  1610013300  1610049100   NaN  303-1_변경   89.0
167  1610049100  1610170800  1610068500   NaN  303-1_변경   90.0
149  1610068500  1610167100  1610049200   NaN  303-1_변경   91.0
165  1610049200  1610144200  1610049500   NaN  303-1_변경   92.0
163  1610049500  1610143900  1610049000   NaN  303-1_변경   93.0
168  1610049000  1610170900  1610067600   NaN  303-1_변경   94.0
152  1610067600  1610168400  1610010000   NaN  303-1_변경   95.0
187  1610010000  1610170200  1610068800   NaN  303-1_변경   96.0
146  1610068800  1610166400  1610010000   NaN  303-1_변경   97.0

[97 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
185  1610010000  1610200100  1610067600   NaN  303-1_변경    NaN
186  1610010000  1610170300  1610068700   NaN  303-1_변경    NaN
188  1610010000  1610149500  1610051200   NaN  303-1_변경    NaN
ROW_ID: 188
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
116  1640039000  1640127700  1610067100   NaN  303-1_변경   71.0
154  1610067100  1610175100  1610064700   NaN  303-1_변경   72.0
155  1610064700  1610215200  1610002700   NaN  303-1_변경   73.0
199  1610002700  1610216700  1610062300   NaN  303-1_변경   74.0
158  1610062300  1610213000  1610002100   NaN  303-1_변경   75.0
201  1610002100  1610003000  1610020100   NaN  303-1_변경   76.0
180  1610020100  1610055800  1610000800   NaN  303-1_변경   77.0
203  1610000800  1610001300  1610000600   NaN  303-1_변경   78.0
205  1610000600  1610000400  1610019900   NaN  303-1_변경   79.0
181  1610019900  1610071900  1610025900   NaN  303-1_변경   80.0
175  1610025900  1610072500  1610026100   NaN  303-1_변경   81.0
173  1610026100  1610072600  1610025500   NaN  303-1_변경   82.0
178  1610025500  1610072100  1610005800   NaN  303-1_변경   83.0
190  1610005800  1610020000  1610006500   NaN  303-1_변경   84.0
189  1610006500  1610019400  1610019300   NaN  303-1_변경   85.0
183  1610019300  1610053200  1610019200   NaN  303-1_변경   86.0
184  1610019200  1610053400  1610005500   NaN  303-1_변경   87.0
191  1610005500  1610015800  1610004200   NaN  303-1_변경   88.0
195  1610004200  1610013300  1610049100   NaN  303-1_변경   89.0
167  1610049100  1610170800  1610068500   NaN  303-1_변경   90.0
149  1610068500  1610167100  1610049200   NaN  303-1_변경   91.0
165  1610049200  1610144200  1610049500   NaN  303-1_변경   92.0
163  1610049500  1610143900  1610049000   NaN  303-1_변경   93.0
168  1610049000  1610170900  1610067600   NaN  303-1_변경   94.0
152  1610067600  1610168400  1610010000   NaN  303-1_변경   95.0
187  1610010000  1610170200  1610068800   NaN  303-1_변경   96.0
146  1610068800  1610166400  1610010000   NaN  303-1_변경   97.0
188  1610010000  1610149500  1610051200   NaN  303-1_변경   98.0
161  1610051200  1610214400  1610069100   NaN  303-1_변경   99.0
145  1610069100  1610216400  1610010000   NaN  303-1_변경  100.0

[100 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
185  1610010000  1610200100  1610067600   NaN  303-1_변경    NaN
186  1610010000  1610170300  1610068700   NaN  303-1_변경    NaN
ROW_ID: 186
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
4    1660002700  1660000400  1660030800   NaN  303-1_변경    1.0
0    1660030800  1660097200  1660000300   NaN  303-1_변경    2.0
6    1660000300  1660000100  1660019700   NaN  303-1_변경    3.0
2    1660019700  1660061200  1660000200   NaN  303-1_변경    4.0
8    1660000200  1650010300  1650004300   NaN  303-1_변경    5.0
79   1650004300  1650009900  1650004200   NaN  303-1_변경    6.0
80   1650004200  1650020900  1650004000   NaN  303-1_변경    7.0
83   1650004000  1650009200  1650003900   NaN  303-1_변경    8.0
84   1650003900  1650182200  1650053700   NaN  303-1_변경    9.0
12   1650053700  1650182300  1650003600   NaN  303-1_변경   10.0
87   1650003600  1650008400  1650034900   NaN  303-1_변경   11.0
28   1650034900  1650113900  1650003400   NaN  303-1_변경   12.0
89   1650003400  1650008000  1650003300   NaN  303-1_변경   13.0
91   1650003300  1650007800  1650003200   NaN  303-1_변경   14.0
93   1650003200  1650007600  1650003100   NaN  303-1_변경   15.0
94   1650003100  1650018600  1650024800   NaN  303-1_변경   16.0
59   1650024800  1650080000  1650016100   NaN  303-1_변경   17.0
60   1650016100  1650053600  1650015400   NaN  303-1_변경   18.0
63   1650015400  1650053200  1650015200   NaN  303-1_변경   19.0
65   1650015200  1650051400  1650014600   NaN  303-1_변경   20.0
67   1650014600  1650049100  1650013800   NaN  303-1_변경   21.0
69   1650013800  1650046000  1650051700   NaN  303-1_변경   22.0
17   1650051700  1650154600  1650012400   NaN  303-1_변경   23.0
71   1650012400  1650042900  1650011200   NaN  303-1_변경   24.0
73   1650011200  1650030900  1650028300   NaN  303-1_변경   25.0
53   1650028300  1650092500  1650028400   NaN  303-1_변경   26.0
50   1650028400  1650092400  1650029900   NaN  303-1_변경   27.0
44   1650029900  1650184300  1650053500   NaN  303-1_변경   28.0
15   1650053500  1650183800  1650029700   NaN  303-1_변경   29.0
47   1650029700  1650097400  1650029400   NaN  303-1_변경   30.0
..          ...         ...         ...   ...       ...    ...
181  1610019900  1610071900  1610025900   NaN  303-1_변경   80.0
175  1610025900  1610072500  1610026100   NaN  303-1_변경   81.0
173  1610026100  1610072600  1610025500   NaN  303-1_변경   82.0
178  1610025500  1610072100  1610005800   NaN  303-1_변경   83.0
190  1610005800  1610020000  1610006500   NaN  303-1_변경   84.0
189  1610006500  1610019400  1610019300   NaN  303-1_변경   85.0
183  1610019300  1610053200  1610019200   NaN  303-1_변경   86.0
184  1610019200  1610053400  1610005500   NaN  303-1_변경   87.0
191  1610005500  1610015800  1610004200   NaN  303-1_변경   88.0
195  1610004200  1610013300  1610049100   NaN  303-1_변경   89.0
167  1610049100  1610170800  1610068500   NaN  303-1_변경   90.0
149  1610068500  1610167100  1610049200   NaN  303-1_변경   91.0
165  1610049200  1610144200  1610049500   NaN  303-1_변경   92.0
163  1610049500  1610143900  1610049000   NaN  303-1_변경   93.0
168  1610049000  1610170900  1610067600   NaN  303-1_변경   94.0
152  1610067600  1610168400  1610010000   NaN  303-1_변경   95.0
187  1610010000  1610170200  1610068800   NaN  303-1_변경   96.0
146  1610068800  1610166400  1610010000   NaN  303-1_변경   97.0
188  1610010000  1610149500  1610051200   NaN  303-1_변경   98.0
161  1610051200  1610214400  1610069100   NaN  303-1_변경   99.0
145  1610069100  1610216400  1610010000   NaN  303-1_변경  100.0
186  1610010000  1610170300  1610068700   NaN  303-1_변경  101.0
147  1610068700  1610166500  1610010000   NaN  303-1_변경  102.0
185  1610010000  1610200100  1610067600   NaN  303-1_변경  103.0
151  1610067600  1610170700  1610049000   NaN  303-1_변경  104.0
169  1610049000  1610143500  1610049500   NaN  303-1_변경  105.0
162  1610049500  1610149800  1610049200   NaN  303-1_변경  106.0
164  1610049200  1610165900  1610068500   NaN  303-1_변경  107.0
150  1610068500  1610166700  1610068600   NaN  303-1_변경  108.0
148  1610068600  1610167000  1610003700   NaN  303-1_변경  109.0

[109 rows x 6 columns]
           F_ID     LINK_ID        T_ID  노선ID      노선번호  INDEX
196  1610003700  1610014000  1610004400   NaN  303-1_변경    NaN
197  1610003700  1610006900  1610039800   NaN  303-1_변경    NaN
ROW_ID: 196

In [15]:
df_link_id[np.isnan(df_link_id['INDEX'])].sort_values('INDEX')

,F_ID,LINK_ID,T_ID,경도(생성됨),기하 도형,위도(생성됨),노선ID,노선번호,INDEX,tF_ID,tLINK_ID,tT_ID
0,1680072900,1680231400,1680070700,126.676102,LINESTRING,37.524717,NaN,81(순환),NaN,1680072900,1680231400,1680070700
2,1680072700,1680231000,1680060900,126.625163,LINESTRING,37.554422,NaN,81(순환),NaN,1680072700,1680231000,1680060900
4,1680070600,1680199900,1680072900,126.674339,LINESTRING,37.524752,NaN,81(순환),NaN,1680070600,1680199900,1680072900
5,1680069300,1680204800,1680052200,126.623859,LINESTRING,37.553490,NaN,81(순환),NaN,1680069300,1680204800,1680052200
6,1680060900,1680182800,1680052200,126.624760,LINESTRING,37.554055,NaN,81(순환),NaN,1680060900,1680182800,1680052200
7,1680060800,1680182900,1680072700,126.626625,LINESTRING,37.554794,NaN,81(순환),NaN,1680060800,1680182900,1680072700
8,1680053600,1680200600,1680070600,126.671071,LINESTRING,37.524871,NaN,81(순환),NaN,1680053600,1680200600,1680070600
10,1680052200,1680153000,1680052100,126.626086,LINESTRING,37.554052,NaN,81(순환),NaN,1680052200,1680153000,1680052100
11,1680052100,1680153200,1680048400,126.632830,LINESTRING,37.555439,NaN,81(순환),NaN,1680052100,1680153200,1680048400
12,1680052100,1680152800,1680060800,126.627150,LINESTRING,37.554659,NaN,81(순환),NaN,1680052100,1680152800,1680060800
13,1680048600,1680192900,1680069300,126.621476,LINESTRING,37.546528,NaN,81(순환),NaN,1680048600,1680192900,1680069300
14,1680048400,1680151800,1680042800,126.632706,LINESTRING,37.549281,NaN,81(순환),NaN,1680048400,1680151800,1680042800
19,1680044700,205,56,126.647182,LINESTRING,37.538627,NaN,81(순환),NaN,1680044700,205,56
21,1680044200,1680137300,1680044700,126.642635,LINESTRING,37.539075,NaN,81(순환),NaN,1680044200,1680137300,1680044700
22,1680044100,203,1680044200,126.638601,LINESTRING,37.539083,NaN,81(순환),NaN,1680044100,203,1680044200
25,1680042800,1680130800,1680042700,126.634261,LINESTRING,37.541792,NaN,81(순환),NaN,1680042800,1680130800,1680042700
26,1680042700,1680130100,1680044100,126.636563,LINESTRING,37.540462,NaN,81(순환),NaN,1680042700,1680130100,1680044100
28,1680040800,1680122500,1680038600,126.651616,LINESTRING,37.540356,NaN,81(순환),NaN,1680040800,1680122500,1680038600
29,1680039800,1680115900,1680038300,126.659817,LINESTRING,37.538235,NaN,81(순환),NaN,1680039800,1680115900,1680038300
30,1680038900,1680113500,1680014600,126.662660,LINESTRING,37.527963,NaN,81(순환),NaN,1680038900,1680113500,1680014600
31,1680038800,1680111500,1680038700,126.659857,LINESTRING,37.533072,NaN,81(순환),NaN,1680038800,1680111500,1680038700
32,1680038700,1680111300,1680038100,126.659869,LINESTRING,37.530918,NaN,81(순환),NaN,1680038700,1680111300,1680038100
33,1680038600,1680112200,1680038500,126.654899,LINESTRING,37.540367,NaN,81(순환),NaN,1680038600,1680112200,1680038500
34,1680038500,1680116000,1680039800,126.658179,LINESTRING,37.540350,NaN,81(순환),NaN,1680038500,1680116000,1680039800
35,1680038300,1680111700,1680038800,126.659823,LINESTRING,37.535200,NaN,81(순환),NaN,1680038300,1680111700,1680038800
36,1680038100,1680113700,1680038900,126.661331,LINESTRING,37.529986,NaN,81(순환),NaN,1680038100,1680113700,1680038900
38,1680014600,1680157300,1680053600,126.665994,LINESTRING,37.525405,NaN,81(순환),NaN,1680014600,1680157300,1680053600
40,123,1079,122,126.618539,LINESTRING,37.532911,NaN,81(순환),NaN,123,1079,122
41,122,1078,4,126.618729,LINESTRING,37.536188,NaN,81(순환),NaN,122,1078,4
44,56,207,1680040800,126.650014,LINESTRING,37.539266,NaN,81(순환),NaN,56,207,1680040800
45,4,21,1680048600,126.619698,LINESTRING,37.539775,NaN,81(순환),NaN,4,21,1680048600
46,1680052200,1680153000,1680052100,126.626086,LINESTRING,37.554052,NaN,81(순환),NaN,1680052200,1680153000,1680052100

In [16]:
df_link_id[np.isnan(df_link_id['INDEX']) == False].sort_values('INDEX')

,F_ID,LINK_ID,T_ID,경도(생성됨),기하 도형,위도(생성됨),노선ID,노선번호,INDEX,tF_ID,tLINK_ID,tT_ID
3,1680070700,1680199800,1680072900,126.676105,LINESTRING,37.524797,NaN,81(순환),1.0,1680070700,1680199800,1680072900
1,1680072900,1680231300,1680053600,126.672665,LINESTRING,37.524937,NaN,81(순환),2.0,1680072900,1680231300,1680053600
9,1680053600,1670076400,1680014600,126.666009,LINESTRING,37.525494,NaN,81(순환),3.0,1680053600,1670076400,1680014600
39,1680014600,1067,1680014700,126.656090,LINESTRING,37.526017,NaN,81(순환),4.0,1680014600,1067,1680014700
37,1680014700,1074,119,126.644953,LINESTRING,37.525686,NaN,81(순환),5.0,1680014700,1074,119
42,119,1073,118,126.638100,LINESTRING,37.523710,NaN,81(순환),6.0,119,1073,118
43,118,1070,1680041900,126.634247,LINESTRING,37.522880,NaN,81(순환),7.0,118,1070,1680041900
27,1680041900,1680125800,1680043900,126.633306,LINESTRING,37.524956,NaN,81(순환),8.0,1680041900,1680125800,1680043900
23,1680043900,1680133000,1680044400,126.631063,LINESTRING,37.526011,NaN,81(순환),9.0,1680043900,1680133000,1680044400
20,1680044400,1680133100,1680043800,126.627976,LINESTRING,37.525117,NaN,81(순환),10.0,1680044400,1680133100,1680043800
24,1680043800,1680135000,1680044900,126.625072,LINESTRING,37.524265,NaN,81(순환),11.0,1680043800,1680135000,1680044900
18,1680044900,1680136500,1680045300,126.623310,LINESTRING,37.524970,NaN,81(순환),12.0,1680044900,1680136500,1680045300
16,1680045300,1680136600,1680045200,126.622280,LINESTRING,37.527358,NaN,81(순환),13.0,1680045300,1680136600,1680045200
17,1680045200,1680135500,1680045400,126.620527,LINESTRING,37.528280,NaN,81(순환),14.0,1680045200,1680135500,1680045400
15,1680045400,1080,1680045400,126.619090,LINESTRING,37.529268,NaN,81(순환),15.0,1680045400,1080,1680045400